"""Framework control definitions for Norvik seed data."""

from __future__ import annotations

NIST_CSF2_CONTROLS: list[dict] = [
    {"domain": "Govern", "control_id": "GV.OC-01", "title": "Contexto organizacional", "description": "La misión de la organización se entiende y comunica.", "weight": 3},
    {"domain": "Govern", "control_id": "GV.OC-02", "title": "Partes interesadas internas", "description": "Las partes interesadas internas se entienden y sus expectativas respecto a la ciberseguridad se determinan.", "weight": 2},
    {"domain": "Govern", "control_id": "GV.OC-03", "title": "Partes interesadas externas", "description": "Las partes interesadas externas y sus expectativas se determinan.", "weight": 2},
    {"domain": "Govern", "control_id": "GV.OC-04", "title": "Requisitos legales", "description": "Se identifican y comunican los requisitos legales, regulatorios y contractuales.", "weight": 3},
    {"domain": "Govern", "control_id": "GV.OC-05", "title": "Objetivos de ciberseguridad", "description": "Los objetivos de ciberseguridad se establecen y acuerdan con las partes interesadas.", "weight": 3},
    {"domain": "Govern", "control_id": "GV.RM-01", "title": "Objetivos de gestión de riesgos", "description": "Se establecen objetivos de gestión de riesgos de ciberseguridad.", "weight": 3},
    {"domain": "Govern", "control_id": "GV.RM-02", "title": "Apetito de riesgo", "description": "Se establece y comunica el apetito y tolerancia al riesgo.", "weight": 3},
    {"domain": "Govern", "control_id": "GV.RM-03", "title": "Priorización de riesgos", "description": "Las actividades de gestión de riesgos se priorizan.", "weight": 2},
    {"domain": "Govern", "control_id": "GV.RR-01", "title": "Roles de ciberseguridad", "description": "Se establecen roles, responsabilidades y autoridades de ciberseguridad.", "weight": 3},
    {"domain": "Govern", "control_id": "GV.RR-02", "title": "Accountability", "description": "Se establece accountability para las decisiones de ciberseguridad.", "weight": 2},
    {"domain": "Govern", "control_id": "GV.PO-01", "title": "Política de ciberseguridad", "description": "Existe una política de ciberseguridad establecida y comunicada.", "weight": 3},
    {"domain": "Govern", "control_id": "GV.PO-02", "title": "Revisión de política", "description": "La política se revisa y actualiza periódicamente.", "weight": 2},
    {"domain": "Govern", "control_id": "GV.OV-01", "title": "Supervisión de resultados", "description": "Se supervisa el desempeño de la estrategia de ciberseguridad.", "weight": 2},
    {"domain": "Govern", "control_id": "GV.OV-02", "title": "Mejora continua", "description": "Se revisa y ajusta la estrategia de ciberseguridad.", "weight": 2},
    {"domain": "Govern", "control_id": "GV.SC-01", "title": "Cadena de suministro", "description": "Se establece una estrategia de gestión de riesgos de la cadena de suministro.", "weight": 3},
    {"domain": "Govern", "control_id": "GV.SC-02", "title": "Roles en cadena de suministro", "description": "Se definen roles y responsabilidades en la cadena de suministro.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.AM-01", "title": "Inventario de hardware", "description": "Se mantiene un inventario de hardware autorizado.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.AM-02", "title": "Inventario de software", "description": "Se mantiene un inventario de software autorizado.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.AM-03", "title": "Representación de comunicaciones", "description": "Se documentan flujos de datos y comunicaciones.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.AM-04", "title": "Servicios externos", "description": "Se catalogan servicios externos y sus dependencias.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.AM-05", "title": "Priorización de activos", "description": "Los activos se priorizan según criticidad.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.AM-07", "title": "Inventario de datos", "description": "Se mantiene inventario de datos y metadatos.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.AM-08", "title": "Gestión del ciclo de vida", "description": "Se gestiona el ciclo de vida de activos de hardware, software y datos.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.RA-01", "title": "Identificación de vulnerabilidades", "description": "Se identifican vulnerabilidades en activos.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.RA-02", "title": "Inteligencia de amenazas", "description": "Se recibe y analiza inteligencia de amenazas.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.RA-03", "title": "Identificación de amenazas internas", "description": "Se identifican amenazas internas.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.RA-04", "title": "Impacto potencial", "description": "Se identifican impactos potenciales de amenazas.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.RA-05", "title": "Evaluación de riesgos", "description": "Se evalúan riesgos usando escenarios de amenaza.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.RA-06", "title": "Priorización de riesgos", "description": "Los riesgos se priorizan y documentan.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.RA-07", "title": "Respuesta a riesgos", "description": "Se seleccionan respuestas a riesgos identificados.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.RA-08", "title": "Proceso de gestión de riesgos", "description": "Se establece un proceso de gestión de riesgos.", "weight": 3},
    {"domain": "Identify", "control_id": "ID.RA-09", "title": "Riesgos de cadena de suministro", "description": "Se identifican riesgos de la cadena de suministro.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.RA-10", "title": "Riesgos de terceros", "description": "Se evalúan riesgos de proveedores y socios.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.IM-01", "title": "Mejora de procesos", "description": "Se mejoran procesos de identificación basados en lecciones aprendidas.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.IM-02", "title": "Mejora de evaluación de riesgos", "description": "Se mejora la evaluación de riesgos continuamente.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.IM-03", "title": "Mejora de inventarios", "description": "Se mejora la gestión de inventarios de activos.", "weight": 2},
    {"domain": "Identify", "control_id": "ID.IM-04", "title": "Mejora de respuesta a riesgos", "description": "Se mejora la respuesta a riesgos identificados.", "weight": 2},
    {"domain": "Protect", "control_id": "PR.AA-01", "title": "Gestión de identidades", "description": "Existen identidades gestionadas para personas, servicios y hardware.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.AA-02", "title": "Autenticación", "description": "Se implementa autenticación de identidades.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.AA-03", "title": "Autenticación multifactor", "description": "Se usa MFA para accesos privilegiados y remotos.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.AA-04", "title": "Gestión de credenciales", "description": "Se gestionan credenciales de forma segura.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.AA-05", "title": "Control de acceso", "description": "Se implementa control de acceso basado en roles.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.AA-06", "title": "Revisión de accesos", "description": "Se revisan accesos periódicamente.", "weight": 2},
    {"domain": "Protect", "control_id": "PR.AT-01", "title": "Concienciación", "description": "Existe programa de concienciación en ciberseguridad.", "weight": 2},
    {"domain": "Protect", "control_id": "PR.AT-02", "title": "Formación especializada", "description": "Personal con roles especializados recibe formación.", "weight": 2},
    {"domain": "Protect", "control_id": "PR.DS-01", "title": "Protección de datos en reposo", "description": "Los datos en reposo están protegidos.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.DS-02", "title": "Protección de datos en tránsito", "description": "Los datos en tránsito están protegidos.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.DS-10", "title": "Cifrado", "description": "Se usa cifrado según política.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.DS-11", "title": "Copias de seguridad", "description": "Existen copias de seguridad y se prueban.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.PS-01", "title": "Gestión de configuración", "description": "Se gestionan configuraciones de sistemas.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.PS-02", "title": "Hardening", "description": "Se aplican configuraciones seguras (hardening).", "weight": 3},
    {"domain": "Protect", "control_id": "PR.PS-03", "title": "Gestión de parches", "description": "Se gestionan parches de seguridad.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.PS-04", "title": "Registro y auditoría", "description": "Se registran eventos de seguridad.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.PS-05", "title": "Protección de logs", "description": "Los registros están protegidos contra alteración.", "weight": 2},
    {"domain": "Protect", "control_id": "PR.PS-06", "title": "Desarrollo seguro", "description": "Se integra seguridad en el ciclo de desarrollo.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.IR-01", "title": "Plan de respuesta", "description": "Existe plan de respuesta a incidentes.", "weight": 3},
    {"domain": "Protect", "control_id": "PR.IR-02", "title": "Comunicación de incidentes", "description": "Se establecen canales de comunicación para incidentes.", "weight": 2},
    {"domain": "Detect", "control_id": "DE.AE-01", "title": "Baseline de red", "description": "Se establece baseline de actividad de red.", "weight": 2},
    {"domain": "Detect", "control_id": "DE.AE-02", "title": "Análisis de eventos", "description": "Se analizan eventos detectados.", "weight": 3},
    {"domain": "Detect", "control_id": "DE.AE-03", "title": "Correlación de eventos", "description": "Se correlacionan eventos de múltiples fuentes.", "weight": 3},
    {"domain": "Detect", "control_id": "DE.AE-04", "title": "Impacto de eventos", "description": "Se determina el impacto de eventos detectados.", "weight": 2},
    {"domain": "Detect", "control_id": "DE.AE-06", "title": "Información de detección", "description": "Se proporciona información de detección a partes relevantes.", "weight": 2},
    {"domain": "Detect", "control_id": "DE.AE-07", "title": "Inteligencia de detección", "description": "Se integra inteligencia de amenazas en detección.", "weight": 2},
    {"domain": "Detect", "control_id": "DE.AE-08", "title": "Detección de anomalías", "description": "Se detectan anomalías en actividad.", "weight": 3},
    {"domain": "Detect", "control_id": "DE.CM-01", "title": "Monitoreo de red", "description": "Se monitorea la red para detectar eventos.", "weight": 3},
    {"domain": "Detect", "control_id": "DE.CM-02", "title": "Monitoreo de entorno físico", "description": "Se monitorea el entorno físico.", "weight": 2},
    {"domain": "Detect", "control_id": "DE.CM-03", "title": "Monitoreo de personal", "description": "Se monitorea actividad de usuarios según política.", "weight": 2},
    {"domain": "Detect", "control_id": "DE.CM-06", "title": "Monitoreo externo", "description": "Se monitorea presencia externa de la organización.", "weight": 2},
    {"domain": "Detect", "control_id": "DE.CM-09", "title": "Detección de malware", "description": "Se detecta código malicioso.", "weight": 3},
    {"domain": "Respond", "control_id": "RS.MA-01", "title": "Plan de respuesta ejecutado", "description": "Se ejecuta el plan de respuesta a incidentes.", "weight": 3},
    {"domain": "Respond", "control_id": "RS.MA-02", "title": "Coordinación de respuesta", "description": "Se coordina respuesta entre equipos.", "weight": 2},
    {"domain": "Respond", "control_id": "RS.MA-03", "title": "Análisis forense", "description": "Se realiza análisis forense cuando procede.", "weight": 2},
    {"domain": "Respond", "control_id": "RS.MA-04", "title": "Mitigación de incidentes", "description": "Se mitigan incidentes activos.", "weight": 3},
    {"domain": "Respond", "control_id": "RS.MA-05", "title": "Comunicación externa", "description": "Se comunica con partes externas durante incidentes.", "weight": 2},
    {"domain": "Respond", "control_id": "RS.AN-01", "title": "Notificaciones", "description": "Se realizan notificaciones requeridas.", "weight": 3},
    {"domain": "Respond", "control_id": "RS.AN-02", "title": "Análisis de impacto", "description": "Se analiza el impacto del incidente.", "weight": 3},
    {"domain": "Respond", "control_id": "RS.AN-03", "title": "Análisis de causa raíz", "description": "Se determina la causa raíz del incidente.", "weight": 3},
    {"domain": "Respond", "control_id": "RS.AN-06", "title": "Acciones post-incidente", "description": "Se definen acciones tras el incidente.", "weight": 2},
    {"domain": "Respond", "control_id": "RS.AN-07", "title": "Lecciones aprendidas", "description": "Se documentan lecciones aprendidas.", "weight": 2},
    {"domain": "Respond", "control_id": "RS.AN-08", "title": "Evidencia de incidentes", "description": "Se preserva evidencia del incidente.", "weight": 2},
    {"domain": "Respond", "control_id": "RS.CO-02", "title": "Comunicación interna", "description": "Se coordina comunicación interna durante incidentes.", "weight": 2},
    {"domain": "Respond", "control_id": "RS.CO-03", "title": "Comunicación con autoridades", "description": "Se comunica con autoridades cuando es requerido.", "weight": 3},
    {"domain": "Respond", "control_id": "RS.MI-01", "title": "Mejora de respuesta", "description": "Se mejora el plan de respuesta continuamente.", "weight": 2},
    {"domain": "Recover", "control_id": "RC.RP-01", "title": "Plan de recuperación", "description": "Existe plan de recuperación ejecutado.", "weight": 3},
    {"domain": "Recover", "control_id": "RC.RP-02", "title": "Priorización de recuperación", "description": "Se priorizan activos para recuperación.", "weight": 2},
    {"domain": "Recover", "control_id": "RC.RP-03", "title": "Restauración de sistemas", "description": "Se restauran sistemas afectados.", "weight": 3},
    {"domain": "Recover", "control_id": "RC.RP-04", "title": "Verificación post-recuperación", "description": "Se verifica integridad tras recuperación.", "weight": 2},
    {"domain": "Recover", "control_id": "RC.RP-05", "title": "Comunicación de recuperación", "description": "Se comunica estado de recuperación.", "weight": 2},
    {"domain": "Recover", "control_id": "RC.RP-06", "title": "Criterios de finalización", "description": "Se definen criterios de finalización de recuperación.", "weight": 2},
    {"domain": "Recover", "control_id": "RC.CO-03", "title": "Comunicación post-recuperación", "description": "Se comunica con partes interesadas tras recuperación.", "weight": 2},
    {"domain": "Recover", "control_id": "RC.CO-04", "title": "Reputación pública", "description": "Se gestiona reputación tras incidente mayor.", "weight": 2},
]

ISO27001_CONTROLS: list[dict] = [
    {"domain": "Organizativos", "control_id": "A.5.1", "title": "Políticas de seguridad", "description": "Políticas de seguridad de la información definidas y aprobadas.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.2", "title": "Roles y responsabilidades", "description": "Roles y responsabilidades de seguridad definidos.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.3", "title": "Segregación de funciones", "description": "Funciones conflictivas segregadas.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.4", "title": "Responsabilidades de gestión", "description": "La dirección exige cumplimiento de políticas.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.5", "title": "Contacto con autoridades", "description": "Contacto con autoridades y grupos de interés.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.6", "title": "Contacto con grupos especiales", "description": "Contacto con grupos de seguridad y foros.", "weight": 1},
    {"domain": "Organizativos", "control_id": "A.5.7", "title": "Inteligencia de amenazas", "description": "Información sobre amenazas recopilada y analizada.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.8", "title": "Seguridad en gestión de proyectos", "description": "Seguridad integrada en gestión de proyectos.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.9", "title": "Inventario de activos", "description": "Inventario de activos de información.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.10", "title": "Uso aceptable", "description": "Reglas de uso aceptable de activos.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.11", "title": "Devolución de activos", "description": "Activos devueltos al cambio o terminación.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.12", "title": "Clasificación de información", "description": "Información clasificada según necesidades.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.13", "title": "Etiquetado de información", "description": "Procedimientos de etiquetado implementados.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.14", "title": "Transferencia de información", "description": "Reglas para transferencia de información.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.15", "title": "Control de acceso", "description": "Reglas de control de acceso establecidas.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.16", "title": "Gestión de identidades", "description": "Ciclo de vida de identidades gestionado.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.17", "title": "Información de autenticación", "description": "Asignación y gestión segura de credenciales.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.18", "title": "Derechos de acceso", "description": "Derechos de acceso provisionados y revisados.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.19", "title": "Seguridad con proveedores", "description": "Seguridad en relaciones con proveedores.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.20", "title": "Seguridad en acuerdos", "description": "Requisitos de seguridad en acuerdos con proveedores.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.21", "title": "Seguridad en cadena ICT", "description": "Gestión de riesgos en cadena de suministro ICT.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.22", "title": "Monitoreo de proveedores", "description": "Monitoreo y revisión de servicios de proveedores.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.23", "title": "Seguridad en servicios cloud", "description": "Adquisición, uso y salida de servicios cloud.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.24", "title": "Planificación de respuesta", "description": "Planificación y preparación para incidentes.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.25", "title": "Evaluación de eventos", "description": "Eventos evaluados y clasificados.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.26", "title": "Respuesta a incidentes", "description": "Incidentes respondidos según procedimientos.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.27", "title": "Aprendizaje de incidentes", "description": "Conocimiento de incidentes utilizado para mejorar.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.28", "title": "Recopilación de evidencia", "description": "Evidencia recopilada y preservada.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.29", "title": "Seguridad durante interrupciones", "description": "Seguridad mantenida durante interrupciones.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.30", "title": "Continuidad del negocio ICT", "description": "Continuidad del negocio ICT planificada.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.31", "title": "Requisitos legales", "description": "Requisitos legales identificados y abordados.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.32", "title": "Derechos de propiedad intelectual", "description": "Derechos de PI protegidos.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.33", "title": "Protección de registros", "description": "Registros protegidos contra pérdida y falsificación.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.34", "title": "Privacidad y PII", "description": "Privacidad y PII protegidas según requisitos.", "weight": 3},
    {"domain": "Organizativos", "control_id": "A.5.35", "title": "Revisión independiente", "description": "Enfoque de seguridad revisado independientemente.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.36", "title": "Cumplimiento de políticas", "description": "Cumplimiento de políticas revisado.", "weight": 2},
    {"domain": "Organizativos", "control_id": "A.5.37", "title": "Procedimientos operativos", "description": "Procedimientos operativos documentados.", "weight": 2},
    {"domain": "Personas", "control_id": "A.6.1", "title": "Screening", "description": "Verificación de antecedentes del personal.", "weight": 2},
    {"domain": "Personas", "control_id": "A.6.2", "title": "Términos de empleo", "description": "Contratos incluyen responsabilidades de seguridad.", "weight": 2},
    {"domain": "Personas", "control_id": "A.6.3", "title": "Concienciación y formación", "description": "Personal recibe concienciación y formación.", "weight": 3},
    {"domain": "Personas", "control_id": "A.6.4", "title": "Proceso disciplinario", "description": "Proceso disciplinario por incumplimiento.", "weight": 2},
    {"domain": "Personas", "control_id": "A.6.5", "title": "Responsabilidades post-empleo", "description": "Responsabilidades vigentes tras terminación.", "weight": 2},
    {"domain": "Personas", "control_id": "A.6.6", "title": "Acuerdos de confidencialidad", "description": "Acuerdos de confidencialidad firmados.", "weight": 2},
    {"domain": "Personas", "control_id": "A.6.7", "title": "Trabajo remoto", "description": "Seguridad en trabajo remoto.", "weight": 3},
    {"domain": "Personas", "control_id": "A.6.8", "title": "Reporte de eventos", "description": "Mecanismo para reportar eventos de seguridad.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.1", "title": "Perímetros de seguridad", "description": "Perímetros de seguridad física definidos.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.2", "title": "Controles de acceso físico", "description": "Acceso físico controlado.", "weight": 3},
    {"domain": "Físicos", "control_id": "A.7.3", "title": "Seguridad de oficinas", "description": "Oficinas y salas protegidas.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.4", "title": "Monitoreo físico", "description": "Instalaciones monitoreadas.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.5", "title": "Protección contra amenazas", "description": "Protección contra amenazas físicas y ambientales.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.6", "title": "Trabajo en áreas seguras", "description": "Procedimientos para áreas seguras.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.7", "title": "Escritorio limpio", "description": "Política de escritorio y pantalla limpios.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.8", "title": "Ubicación de equipos", "description": "Equipos ubicados para reducir riesgos.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.9", "title": "Activos fuera de instalaciones", "description": "Activos fuera de instalaciones protegidos.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.10", "title": "Medios de almacenamiento", "description": "Medios gestionados durante ciclo de vida.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.11", "title": "Servicios de soporte", "description": "Servicios de soporte protegidos.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.12", "title": "Cableado", "description": "Cableado de energía y telecom protegido.", "weight": 1},
    {"domain": "Físicos", "control_id": "A.7.13", "title": "Mantenimiento de equipos", "description": "Equipos mantenidos correctamente.", "weight": 2},
    {"domain": "Físicos", "control_id": "A.7.14", "title": "Eliminación segura", "description": "Activos eliminados o reutilizados de forma segura.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.1", "title": "Dispositivos de usuario", "description": "Información en dispositivos de usuario protegida.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.2", "title": "Derechos de acceso privilegiado", "description": "Accesos privilegiados restringidos y gestionados.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.3", "title": "Restricción de acceso", "description": "Acceso a información restringido.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.4", "title": "Código fuente", "description": "Acceso a código fuente controlado.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.5", "title": "Autenticación segura", "description": "Tecnologías de autenticación segura.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.6", "title": "Capacidad", "description": "Uso de recursos monitoreado y ajustado.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.7", "title": "Protección contra malware", "description": "Protección contra malware implementada.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.8", "title": "Gestión de vulnerabilidades", "description": "Vulnerabilidades técnicas gestionadas.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.9", "title": "Gestión de configuración", "description": "Configuraciones establecidas y documentadas.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.10", "title": "Eliminación de información", "description": "Información eliminada cuando ya no se requiere.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.11", "title": "Enmascaramiento de datos", "description": "Enmascaramiento según política.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.12", "title": "Prevención de fuga", "description": "Medidas contra fuga de datos.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.13", "title": "Copias de seguridad", "description": "Copias de seguridad realizadas y probadas.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.14", "title": "Redundancia", "description": "Redundancia de instalaciones de procesamiento.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.15", "title": "Registro", "description": "Registros generados y protegidos.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.16", "title": "Actividades de monitoreo", "description": "Redes y sistemas monitoreados.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.17", "title": "Sincronización de reloj", "description": "Relojes de sistemas sincronizados.", "weight": 1},
    {"domain": "Tecnológicos", "control_id": "A.8.18", "title": "Uso de programas privilegiados", "description": "Uso de utilidades privilegiadas restringido.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.19", "title": "Software en sistemas operativos", "description": "Instalación de software controlada.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.20", "title": "Seguridad de redes", "description": "Redes y servicios de red asegurados.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.21", "title": "Seguridad de servicios de red", "description": "Servicios de red identificados y asegurados.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.22", "title": "Segregación de redes", "description": "Grupos de servicios segregados en redes.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.23", "title": "Filtrado web", "description": "Acceso a sitios externos gestionado.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.24", "title": "Criptografía", "description": "Uso efectivo de criptografía.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.25", "title": "Ciclo de vida de desarrollo seguro", "description": "Seguridad en ciclo de vida de desarrollo.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.26", "title": "Requisitos de seguridad de aplicaciones", "description": "Requisitos de seguridad identificados.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.27", "title": "Arquitectura segura", "description": "Principios de arquitectura segura aplicados.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.28", "title": "Codificación segura", "description": "Principios de codificación segura aplicados.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.29", "title": "Pruebas de seguridad", "description": "Pruebas de seguridad en desarrollo.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.30", "title": "Desarrollo externalizado", "description": "Desarrollo externalizado dirigido y monitoreado.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.31", "title": "Separación de entornos", "description": "Entornos de desarrollo, prueba y producción separados.", "weight": 3},
    {"domain": "Tecnológicos", "control_id": "A.8.32", "title": "Gestión de cambios", "description": "Cambios en instalaciones controlados.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.33", "title": "Información de prueba", "description": "Información de prueba protegida.", "weight": 2},
    {"domain": "Tecnológicos", "control_id": "A.8.34", "title": "Protección en auditoría", "description": "Actividades de auditoría planificadas.", "weight": 2},
]

CIS_V8_CONTROLS: list[dict] = [
    {"domain": "CIS 1", "control_id": "CIS-1.1", "title": "Inventario de activos empresariales", "description": "Establecer y mantener un inventario detallado de activos.", "weight": 3},
    {"domain": "CIS 1", "control_id": "CIS-1.2", "title": "Inventario de software", "description": "Inventario de software autorizado.", "weight": 3},
    {"domain": "CIS 1", "control_id": "CIS-1.3", "title": "Utilizar herramientas de descubrimiento", "description": "Utilizar herramientas activas de descubrimiento.", "weight": 2},
    {"domain": "CIS 2", "control_id": "CIS-2.1", "title": "Software de inventario autorizado", "description": "Solo software autorizado instalado.", "weight": 3},
    {"domain": "CIS 2", "control_id": "CIS-2.2", "title": "Lista de permitidos de software", "description": "Lista de permitidos implementada.", "weight": 3},
    {"domain": "CIS 2", "control_id": "CIS-2.3", "title": "Lista de bloqueados", "description": "Lista de bloqueados implementada.", "weight": 2},
    {"domain": "CIS 3", "control_id": "CIS-3.1", "title": "Gestión de vulnerabilidades", "description": "Proceso de gestión de vulnerabilidades establecido.", "weight": 3},
    {"domain": "CIS 3", "control_id": "CIS-3.2", "title": "Escaneo de vulnerabilidades", "description": "Escaneo regular de vulnerabilidades.", "weight": 3},
    {"domain": "CIS 3", "control_id": "CIS-3.3", "title": "Remediación de vulnerabilidades", "description": "Remediar vulnerabilidades según SLA.", "weight": 3},
    {"domain": "CIS 4", "control_id": "CIS-4.1", "title": "Inventario de cuentas administrativas", "description": "Inventario de cuentas administrativas.", "weight": 3},
    {"domain": "CIS 4", "control_id": "CIS-4.2", "title": "Cambio de credenciales por defecto", "description": "Cambiar credenciales por defecto.", "weight": 3},
    {"domain": "CIS 4", "control_id": "CIS-4.3", "title": "MFA en accesos administrativos", "description": "MFA en accesos administrativos.", "weight": 3},
    {"domain": "CIS 5", "control_id": "CIS-5.1", "title": "Inventario de cuentas", "description": "Inventario de cuentas de usuario.", "weight": 2},
    {"domain": "CIS 5", "control_id": "CIS-5.2", "title": "Cuentas únicas", "description": "Cuentas únicas por usuario.", "weight": 2},
    {"domain": "CIS 5", "control_id": "CIS-5.3", "title": "Desactivar cuentas inactivas", "description": "Desactivar cuentas inactivas en 45 días.", "weight": 2},
    {"domain": "CIS 6", "control_id": "CIS-6.1", "title": "Registro de accesos", "description": "Registrar accesos a sistemas críticos.", "weight": 3},
    {"domain": "CIS 6", "control_id": "CIS-6.2", "title": "Revisión de logs", "description": "Revisar logs de acceso regularmente.", "weight": 2},
    {"domain": "CIS 6", "control_id": "CIS-6.3", "title": "Sincronización de tiempo", "description": "Sincronizar relojes de sistemas.", "weight": 1},
    {"domain": "CIS 7", "control_id": "CIS-7.1", "title": "Protección contra malware", "description": "Software antimalware en todos los activos.", "weight": 3},
    {"domain": "CIS 7", "control_id": "CIS-7.2", "title": "Actualización de firmas", "description": "Actualizar firmas antimalware automáticamente.", "weight": 3},
    {"domain": "CIS 8", "control_id": "CIS-8.1", "title": "Recuperación de datos", "description": "Proceso de recuperación de datos establecido.", "weight": 3},
    {"domain": "CIS 8", "control_id": "CIS-8.2", "title": "Copias de seguridad", "description": "Realizar copias de seguridad periódicas.", "weight": 3},
    {"domain": "CIS 8", "control_id": "CIS-8.3", "title": "Prueba de restauración", "description": "Probar restauración de copias.", "weight": 2},
    {"domain": "CIS 9", "control_id": "CIS-9.1", "title": "Controles de acceso a red", "description": "Controles de acceso a la red implementados.", "weight": 3},
    {"domain": "CIS 9", "control_id": "CIS-9.2", "title": "Firewalls en dispositivos", "description": "Firewalls en dispositivos de usuario.", "weight": 2},
    {"domain": "CIS 10", "control_id": "CIS-10.1", "title": "Respaldos de configuración", "description": "Respaldar configuraciones de red.", "weight": 2},
    {"domain": "CIS 10", "control_id": "CIS-10.2", "title": "Configuración segura", "description": "Configuraciones seguras en dispositivos de red.", "weight": 3},
    {"domain": "CIS 11", "control_id": "CIS-11.1", "title": "Estándares de configuración", "description": "Estándares de configuración segura establecidos.", "weight": 3},
    {"domain": "CIS 11", "control_id": "CIS-11.2", "title": "Hardening de servidores", "description": "Hardening en servidores.", "weight": 3},
    {"domain": "CIS 12", "control_id": "CIS-12.1", "title": "Gestión de parches", "description": "Proceso de gestión de parches establecido.", "weight": 3},
    {"domain": "CIS 12", "control_id": "CIS-12.2", "title": "Parches en 30 días", "description": "Aplicar parches críticos en 30 días.", "weight": 3},
    {"domain": "CIS 13", "control_id": "CIS-13.1", "title": "Programa de concienciación", "description": "Programa de concienciación en seguridad.", "weight": 2},
    {"domain": "CIS 13", "control_id": "CIS-13.2", "title": "Simulaciones de phishing", "description": "Simulaciones periódicas de phishing.", "weight": 2},
    {"domain": "CIS 14", "control_id": "CIS-14.1", "title": "Plan de respuesta a incidentes", "description": "Plan de respuesta a incidentes documentado.", "weight": 3},
    {"domain": "CIS 14", "control_id": "CIS-14.2", "title": "Equipo de respuesta", "description": "Equipo de respuesta designado.", "weight": 2},
    {"domain": "CIS 15", "control_id": "CIS-15.1", "title": "Inventario de proveedores", "description": "Inventario de proveedores de servicios.", "weight": 2},
    {"domain": "CIS 15", "control_id": "CIS-15.2", "title": "Evaluación de proveedores", "description": "Evaluar seguridad de proveedores.", "weight": 2},
    {"domain": "CIS 16", "control_id": "CIS-16.1", "title": "Desarrollo seguro", "description": "Prácticas de desarrollo seguro establecidas.", "weight": 3},
    {"domain": "CIS 16", "control_id": "CIS-16.2", "title": "Revisión de código", "description": "Revisión de código de seguridad.", "weight": 2},
    {"domain": "CIS 17", "control_id": "CIS-17.1", "title": "Programa de gestión de incidentes", "description": "Programa formal de gestión de incidentes.", "weight": 3},
    {"domain": "CIS 17", "control_id": "CIS-17.2", "title": "Clasificación de incidentes", "description": "Clasificar y priorizar incidentes.", "weight": 2},
    {"domain": "CIS 18", "control_id": "CIS-18.1", "title": "Penetration testing", "description": "Pruebas de penetración periódicas.", "weight": 2},
    {"domain": "CIS 18", "control_id": "CIS-18.2", "title": "Red team exercises", "description": "Ejercicios de red team periódicos.", "weight": 2},
]

RGPD_CONTROLS: list[dict] = [
    {"domain": "Principios", "control_id": "RGPD-5.1", "title": "Licitud del tratamiento", "description": "¿Existe base legal documentada para cada tratamiento de datos?", "weight": 3},
    {"domain": "Principios", "control_id": "RGPD-5.2", "title": "Limitación de finalidad", "description": "¿Los datos se recogen para fines determinados y legítimos?", "weight": 3},
    {"domain": "Principios", "control_id": "RGPD-5.3", "title": "Minimización de datos", "description": "¿Solo se recogen datos adecuados y necesarios?", "weight": 3},
    {"domain": "Principios", "control_id": "RGPD-5.4", "title": "Exactitud", "description": "¿Existen procedimientos para mantener datos exactos y actualizados?", "weight": 2},
    {"domain": "Principios", "control_id": "RGPD-5.5", "title": "Limitación del plazo", "description": "¿Se definen plazos de conservación y se eliminan datos obsoletos?", "weight": 3},
    {"domain": "Principios", "control_id": "RGPD-5.6", "title": "Integridad y confidencialidad", "description": "¿Se garantiza seguridad adecuada de los datos personales?", "weight": 3},
    {"domain": "Principios", "control_id": "RGPD-5.7", "title": "Responsabilidad proactiva", "description": "¿Se demuestra el cumplimiento de los principios (accountability)?", "weight": 3},
    {"domain": "Privacy by Design", "control_id": "RGPD-25.1", "title": "Privacidad desde el diseño", "description": "¿Se integra la protección de datos desde el diseño de sistemas?", "weight": 3},
    {"domain": "Privacy by Design", "control_id": "RGPD-25.2", "title": "Privacidad por defecto", "description": "¿La configuración por defecto garantiza mínima exposición de datos?", "weight": 3},
    {"domain": "Seguridad", "control_id": "RGPD-32.1", "title": "Medidas técnicas", "description": "¿Existen medidas técnicas adecuadas (cifrado, pseudonimización)?", "weight": 3},
    {"domain": "Seguridad", "control_id": "RGPD-32.2", "title": "Medidas organizativas", "description": "¿Existen medidas organizativas (políticas, formación, accesos)?", "weight": 3},
    {"domain": "Seguridad", "control_id": "RGPD-32.3", "title": "Evaluación periódica", "description": "¿Se evalúan y actualizan las medidas de seguridad periódicamente?", "weight": 2},
    {"domain": "Seguridad", "control_id": "RGPD-32.4", "title": "Notificación de brechas", "description": "¿Existe procedimiento de notificación de brechas en 72h?", "weight": 3},
    {"domain": "DPIA", "control_id": "RGPD-35.1", "title": "Evaluación de impacto", "description": "¿Se realizan EIPD cuando el tratamiento entraña alto riesgo?", "weight": 3},
    {"domain": "DPIA", "control_id": "RGPD-35.2", "title": "Consulta previa", "description": "¿Se consulta a la AEPD cuando procede tras EIPD?", "weight": 2},
    {"domain": "DPIA", "control_id": "RGPD-35.3", "title": "Revisión de EIPD", "description": "¿Se revisan las EIPD cuando cambian los riesgos?", "weight": 2},
    {"domain": "Derechos", "control_id": "RGPD-15.1", "title": "Derecho de acceso", "description": "¿Existe procedimiento para atender solicitudes de acceso?", "weight": 2},
    {"domain": "Derechos", "control_id": "RGPD-17.1", "title": "Derecho de supresión", "description": "¿Se puede suprimir datos cuando procede?", "weight": 2},
    {"domain": "Derechos", "control_id": "RGPD-20.1", "title": "Portabilidad", "description": "¿Se facilita la portabilidad de datos en formato estructurado?", "weight": 2},
    {"domain": "Registro", "control_id": "RGPD-30.1", "title": "Registro de actividades", "description": "¿Existe registro de actividades de tratamiento (RAT)?", "weight": 3},
    {"domain": "Registro", "control_id": "RGPD-30.2", "title": "Contenido del RAT", "description": "¿El RAT incluye finalidades, categorías, plazos y medidas?", "weight": 3},
    {"domain": "DPO", "control_id": "RGPD-37.1", "title": "Delegado de protección de datos", "description": "¿Se ha designado DPO cuando es obligatorio?", "weight": 2},
    {"domain": "Transferencias", "control_id": "RGPD-44.1", "title": "Transferencias internacionales", "description": "¿Las transferencias fuera del EEE tienen garantías adecuadas?", "weight": 3},
    {"domain": "Transferencias", "control_id": "RGPD-46.1", "title": "Cláusulas contractuales", "description": "¿Se usan SCC u otras garantías para transferencias?", "weight": 2},
    {"domain": "Consentimiento", "control_id": "RGPD-7.1", "title": "Consentimiento válido", "description": "¿El consentimiento es libre, específico, informado e inequívoco?", "weight": 3},
]

FRAMEWORKS = {
    "NIST_CSF2": {
        "code": "NIST_CSF2",
        "name": "NIST CSF 2.0",
        "version": "2.0",
        "controls": NIST_CSF2_CONTROLS,
    },
    "ISO27001": {
        "code": "ISO27001",
        "name": "ISO 27001:2022",
        "version": "2022",
        "controls": ISO27001_CONTROLS,
    },
    "CIS_V8": {
        "code": "CIS_V8",
        "name": "CIS Controls v8",
        "version": "8.0",
        "controls": CIS_V8_CONTROLS,
    },
    "RGPD": {
        "code": "RGPD",
        "name": "RGPD",
        "version": "2016/679",
        "controls": RGPD_CONTROLS,
    },
}
